# Generated by Django 5.1.6 on 2025-03-13 21:14

import ckeditor.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_article_meta_description_article_meta_keywords'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='adsenselocation',
            options={'ordering': ['name'], 'verbose_name': 'Locație AdSense', 'verbose_name_plural': 'Locații AdSense'},
        ),
        migrations.AlterModelOptions(
            name='article',
            options={'ordering': ['-created_at'], 'verbose_name': 'Articol', 'verbose_name_plural': 'Articole'},
        ),
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['name'], 'verbose_name': 'Categorie', 'verbose_name_plural': 'Categorii'},
        ),
        migrations.RemoveField(
            model_name='adsenselocation',
            name='description',
        ),
        migrations.RemoveField(
            model_name='article',
            name='is_featured',
        ),
        migrations.RemoveField(
            model_name='category',
            name='description',
        ),
        migrations.AddField(
            model_name='article',
            name='meta_title',
            field=models.CharField(blank=True, max_length=200, verbose_name='Titlu Meta'),
        ),
        migrations.AlterField(
            model_name='adsenselocation',
            name='ad_code',
            field=models.TextField(verbose_name='Cod AdSense'),
        ),
        migrations.AlterField(
            model_name='adsenselocation',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Este activ'),
        ),
        migrations.AlterField(
            model_name='adsenselocation',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Nume locație'),
        ),
        migrations.AlterField(
            model_name='article',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='articles', to='blog.category', verbose_name='Categorie'),
        ),
        migrations.AlterField(
            model_name='article',
            name='content',
            field=ckeditor.fields.RichTextField(verbose_name='Conținut'),
        ),
        migrations.AlterField(
            model_name='article',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Data creării'),
        ),
        migrations.AlterField(
            model_name='article',
            name='featured_image',
            field=models.ImageField(upload_to='articles/', verbose_name='Imagine principală'),
        ),
        migrations.AlterField(
            model_name='article',
            name='meta_description',
            field=models.TextField(blank=True, default=1, verbose_name='Descriere Meta'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='article',
            name='meta_keywords',
            field=models.CharField(blank=True, default=1, max_length=200, verbose_name='Cuvinte cheie Meta'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='article',
            name='read_time',
            field=models.IntegerField(default=5, verbose_name='Timp de citire (minute)'),
        ),
        migrations.AlterField(
            model_name='article',
            name='slug',
            field=models.SlugField(unique=True, verbose_name='Slug'),
        ),
        migrations.AlterField(
            model_name='article',
            name='title',
            field=models.CharField(max_length=200, verbose_name='Titlu'),
        ),
        migrations.AlterField(
            model_name='article',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Data actualizării'),
        ),
        migrations.AlterField(
            model_name='category',
            name='icon',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Iconiță FontAwesome'),
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Nume'),
        ),
        migrations.AlterField(
            model_name='category',
            name='slug',
            field=models.SlugField(unique=True, verbose_name='Slug'),
        ),
    ]
