# Generated by Django 5.1.6 on 2025-04-02 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_category_description_alter_article_slug_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='Telefon')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email')),
                ('address', models.TextField(blank=True, verbose_name='Adresă')),
                ('facebook_url', models.URLField(blank=True, verbose_name='Link Facebook')),
                ('instagram_url', models.URLField(blank=True, verbose_name='Link Instagram')),
                ('youtube_url', models.URLField(blank=True, verbose_name='Link YouTube')),
            ],
            options={
                'verbose_name': 'Setări Site',
                'verbose_name_plural': 'Setări Site',
            },
        ),
    ]
